---
driver:
  name: vagrant
  require_chef_omnibus: 11.16.4

provisioner:
  name: chef_solo
  cookbook_path: cookbooks

platforms:
  - name: ubuntu-14.04

busser:
  sudo: true

suites:
  - name: bootstrap_system
    run_list:
      - [ "recipe[inaturalist-cookbook::bootstrap_system]" ]
    attributes: {
      omnibus_updater: {
        version: "11.16.4"
      },
      authorization: {
        sudo: {
          users: [ "vagrant" ],
          passwordless: true
        }
      }
    }
